- hosts: web_servers
  become: true
  become_method: sudo
  tasks:
    - name: "Install Apache2"
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: "Start Apache2"
      service:
        name: apache2
        state: started
#        update_cache: true


- hosts: haproxy
  become: true
  become_method: sudo
  tasks:
  - name: "Install HAProxy"
    apt:
      name: haproxy
      state: present
      update_cache: true


  - name: "Conf HAProxy"
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: '0664'

  - name: "Start HAProxy"
    service:
      name: haproxy
      state: started

