- name: install apache2
  remote_user: user
  hosts: webserver
  become: true
  become_method: sudo
#  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      apt:
        name: apache2
        state: present
    - name: "Start Apache service"
      service:
        name: apache2
        state: started
